CREATE TABLE TB_ORDER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TOTAL_PRICE DECIMAL(10,2),
    CREATED_AT DATETIME,
    USER_ID INT,
    ORDER_STATUS VARCHAR(20)
);

CREATE TABLE TB_PRODUCT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(200),
    PRICE DECIMAL(10,2)
);

CREATE TABLE TB_ORDER_ITEM (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    TOTAL_PRICE DECIMAL(10,2),

    CONSTRAINT FK_TB_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES TB_ORDER(ID),
    CONSTRAINT FK_TB_ORDER_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES TB_PRODUCT(ID)
);

INSERT INTO TB_PRODUCT (ID, DESCRIPTION, PRICE) VALUES (1, "BANANA", 1.0);
INSERT INTO TB_PRODUCT (ID, DESCRIPTION, PRICE) VALUES (2, "ABACAXI", 3.0);
INSERT INTO TB_PRODUCT (ID, DESCRIPTION, PRICE) VALUES (3, "PERA", 4.0);
INSERT INTO TB_PRODUCT (ID, DESCRIPTION, PRICE) VALUES (4, "MELANCIA", 11.0);
INSERT INTO TB_PRODUCT (ID, DESCRIPTION, PRICE) VALUES (5, "ABACATE", 7.0);
INSERT INTO TB_PRODUCT (ID, DESCRIPTION, PRICE) VALUES (6, "LIMAO", 20.0);